### ISSUE TITLE
Add audio to the animations automatically using ffmpeg

### ISSUE THREAD

**Issue by kabachuha** [deforum/stable-diffusion#100]
As you know, the users often use Deforum animations for music clip production. To make the process more easy, an audio can be attached to the resulting video file using built-in ffmpeg functionality

https://stackoverflow.com/questions/11779490/how-to-add-a-new-audio-not-mixing-into-a-video-using-ffmpeg

---

one of the problems from the list #97

**Comment by taal10** [comment]
you can actually also use the python librosa library to find something like the beat timestamps within a song...and then make all of those the keyframes :)
