### ISSUE TITLE
Reformat README to suit Deforum better

### ISSUE THREAD

**Issue by kabachuha** [deforum/stable-diffusion#105]
Right now the README file is the same as the original Stable Diffusion now. For better work with the audience, we should customize it with the description of that Deforum does and how to setup it locally

**Comment by y0himba** [comment]
On this, the install section says for Windows Users that the models need to be downloaded and place in the correct directories. The directories don't exist?  Are we to clone the original SD repo as well?  If so, where do we place it?

There are no `models` or `pretrained` directories.  I am probably quite new at this in comparison, however, folks like myself would love to learn about this.  It may set us on a path to learning about more.

**Comment by deforum** [comment]
all you need to do is clone the local repo. running the .py or .ipynb will create the pretrained and models folder for you.

**Comment by codefaux** [comment]
Can anyone point me to a list of what's actually been changed? I found this sideband blind, I'm betting I'm not alone. At least if it's mentioned here, it exists visibly until it's properly written up.
