### ISSUE TITLE
Using v1.5

### ISSUE THREAD

**Issue by diach0** [deforum/stable-diffusion#133]
Hi!
Love the deforum stable diffusion notebook, in my experience it's the best one to make videos and other uses.
Is it possible to use v1.5 in the current version of the notebook? Maybe using the custom option? I've tried but haven't been successful yet.
Thank you so much for all your amazing work.

**Comment by deforum** [comment]
you can use this notebook
https://colab.research.google.com/github/deforum-art/deforum-stable-diffusion/blob/main/Deforum_Stable_Diffusion.ipynb
