### ISSUE TITLE
'use_depth_warping' error

### ISSUE THREAD

**Issue by bijlevel** [deforum/stable-diffusion#134]
Whenever I uncheck  'use_depth_warping ' (in 3D animation mode) I get an error, see screen shot. This happens after SD has generated the first frame. When I check 'use_depth_warping' I get no error and the animation is generated without problems, but (indeed) it is an animation with warping., which I find ugly. What could cause this error?

<img width="1323" alt="Screenshot 2022-11-09 at 20 42 37" src="https://user-images.githubusercontent.com/11859363/200930393-6eac0c90-bf29-4d33-a688-439e7f17b409.png">

**Comment by bijlevel** [comment]
No comments so far, while I think this really is a bug or at least the developer(s) need to inspect the code for errors...

**Comment by deforum** [comment]
i am not an expert on this but i dont think you can use 3d without depth warp

**Comment by bijlevel** [comment]
You're probably right, but why then the option to uncheck it? If I uncheck it, I get an error.

**Comment by pharmapsychotic** [comment]
Fixing now...

**Comment by bijlevel** [comment]
Thanks and good luck!

**Comment by bijlevel** [comment]
I still get the error. I'm using the google collab version though, so maybe that is the reason. I did download the latest ckpt v1-4, but that didn't help either.

**Comment by pharmapsychotic** [comment]
hey @bijlevel the fix is in the 0.6 release which is now in this repo https://github.com/deforum-art/deforum-stable-diffusion

**Comment by bijlevel** [comment]
@pharmapsychotic OK, but since I'm on Mac and therefore can't run SD locally, can you explain how to run this version in a Google colab environment (if that's how you call it... :-)). TIA!

**Comment by bijlevel** [comment]
I did find the link to SD colab v0.6. Will try this out asap! Thanks for your efforts!

**Comment by bijlevel** [comment]
Well, I tried to use this version, but I'm stuck at the license requirement. Nowhere can I find a way (or button) to accept the license. I do have a Huggingfaec account and did generate a token... (Never had this problem with v0.5)

**Comment by bijlevel** [comment]
Again, I keep getting an error telling me I need to accept "the" license for using v 0.6, but no way I can find the way to accept a license! See attachment for info about the error. Please help!

<img width="912" alt="Screenshot 2022-11-20 at 10 14 32" src="https://user-images.githubusercontent.com/11859363/202894526-f323372f-5d61-491c-b8a0-256d5e49226e.png">

**Comment by bijlevel** [comment]
Finally I noticed v0.6 needs model v1.5, while I still had model v1.4. I did download the v1.5 model after accepting the license and now v0.6 is happily generating AI-art. First impressions of the results are quite promising!
