### ISSUE TITLE
Does strength_schedule actually work?

### ISSUE THREAD

**Issue by enn-nafnlaus** [deforum/stable-diffusion#136]
From the manual, I expect strength_schedule to be akin to denoising strength, and thus "0: (0)" should lead to no change between frames (lacking any other transformation and with noise_schedule also 0).  Except that's not what happens - strength schedule "0: (0)" still leads to the image dancing around with each frame, like it's generating entire new images rather than img2img'ing the previous frame.

Am I doing something wrong or what?  I'm using the AUTOMATIC1111 Deforum plugin, fetched yesterday.

The idea was to have a very low denoising strength to increase frame-to-frame consistency without the heavy dragging effect of diffusion_cadence. But that doesn't appear to be possible.

**Comment by kabachuha** [comment]
it's the reverse of 'denoising_strength', that change is made to keep it consistent with the Deforum Colab notebook.

```
    denoising_strength = 1 - strength
```

meaning 0 means max change, 1 - zero diffusion passes

**Comment by enn-nafnlaus** [comment]
I already considered that possibility and tried setting it to 1.0.  Still changes radically every frame. Try it yourself.

**Comment by rewbs** [comment]
For reference for others landing here there's further discussion in this thread: https://github.com/deforum-art/deforum-for-automatic1111-webui/issues/3#issuecomment-1347770460

> Try it yourself.

If it's any reassurance, I can confirm many dozens of users at least (myself included) are happily generating animations with fully operational strength settings, so I'm sure we'll figure this out together. :)

**Comment by quoctu03** [comment]
Uploading BMjAyMjA4MDMwMTIxMTNfNDM4NzY5Nzk3XzgwODI4MDYyMzQxXzFfMw==_b_B82f7f67c512a9241690542a188a0da09.mp4…

**Comment by quoctu03** [comment]
![797DFAA0-A2BA-491A-BF94-9C189F373951](https://user-images.githubusercontent.com/132362328/235670664-6af60edb-0974-4614-815a-90c188dea535.jpeg)

**Comment by kabachuha** [comment]
Spam
