### ISSUE TITLE
Implement VRAM optimizations for the local build

### ISSUE THREAD

**Issue by kabachuha** [deforum/stable-diffusion#99]
As you know, deforum making its own local build. For it to be launchable at as many platforms as possible, we may want to implement optional lower VRAM optimizations. You can use this branch as a starting point and then progress to the newer ones made at external SD forks

https://github.com/kabachuha/stable-diffusion/commit/d8550474d76ca6593aba02031fc197f5db26204a

**Comment by pablopub** [comment]
Hello, @kabachuha!

When I stopped the local notebook and tried to rerun it, I got the Out-of-memory error on my RTX 3070 ti 8 GB (having to resort to a cumbersome notebook restart to clear the memory).

The solution I found to get rid of the OOM error is to run gc.collect() and torch.cuda.empty_cache() **before** every run (I think those commands are also run after successful completion, but I canceled more times than not to fine-tune).

Hope this is useful.

**Comment by pablopub** [comment]
Things are much better after xformers!
